azure: {timeout_minutes: 600}
build_platform: {osx_arm64: osx_64}
conda_forge_output_validation: true
idle_timeout_minutes: 90
provider: {linux_aarch64: default, linux_ppc64le: azure, win: azure}
test_on_native_only: true
